name: freelec-springboot2-webservice

on:
  push:
    branches:
      - feat/cicd # CI/CD 테스트용 브랜치 TODO 테스트 후 master로 수정
  workflow_dispatch: # 수동 실행

jobs:
  run-shell-command:
    runs-on: ubuntu-latest

    steps:
      - name: chmod script
        run: chmod -755 deploy.sh
        shell: bash

      - name: run
        run:  deploy.sh
        shell: bash
