name: freelec-springboot2-webservice

on:
  push:
    branches:
      - feat/cicd # CI/CD 테스트용 브랜치 TODO 테스트 후 master로 수정
  workflow_dispatch: # 수동 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: run
        run:  ./deploy.sh
        shell: bash
