name: coinTalk chatRoom server CI/CD

on:
  push:
    branches: [ feat/cicd ]
  pull_request:
    branches: [ feat/cicd ]

env:
  S3_BUCKET_NAME: fullbang-production-deploy

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Adding secret
        run: |
          echo $DB_INFO >> src/main/resources/application.properties
          cat src/main/resources/application.properties
        shell: bash
        env:
          DB_INFO: ${{secrets.DB_SECRET_INFO}}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build