name: coinTalk chatRoom server CI/CD

on:
  push:
    branches: [ feat/cicd ]
  pull_request:
    branches: [ feat/cicd ]

env:
  S3_BUCKET_NAME: fullbang-production-deploy

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRODUCTION_IP }}
          username: ${{ secrets.PRODUCTION_SSH_ID }}
          key: ${{ secrets.PRODUCTION_SSH_KEY }}
          port: ${{ secrets.PRODUCTION_SSH_PORT }}
          script: |
            whoami